# Basic video info - not used in program  # UPDATE ON NEW VIDEO
video_name = 'Wuhan 3-day travel strategy (+English translations)'
video_description = '''
This video was made for practicing both listening comprehension and character recognition.

It translates a post from 小红书 (Little Red Book) which can be found at http://xhslink.com/o/8XVDOullGyc

The text is generated by an AI agent summarizing recent news on this topic.

Because these videos are programmatically generated, the format is customizable to quickly produce alternate formats, so please let me know if you have any corrections, suggestions, feedback, or questions, please leave a comment.

Python code to produce this video: https://github.com/srcole/my_mandarin_database
'''

# Main settings  # UPDATE ON NEW VIDEO
video_number = '41'
data_settings = {
    'recording_id': 'conly',
    'filename_suffix': 'wuhan_travel',
    'voice_name_zh': 'zh-CN-XiaoyuMultilingualNeural',
    'different_file_name': 'static/texts/lists/20251110_wuhan.csv',
    'sort_keys': ['index'],
    'sort_asc': [True],
}


# Misc properties
output_path = 'output/videos/'
hanzi_font_path = '/System/Library/Fonts/STHeiti Medium.ttc'
DEFAULT_TEXT_PROPERTIES = {
    'font_path': hanzi_font_path,
    'fill': 'black',
    'spacing': 30,
    'align': 'center',
    'font_size': 50,
}

# Aesthetic configs
video_configs = {
    'bg_size': (1280, 720),
    'bg_color': 'white',
    'text_color': 'black',
    'max_line_length_buffer_size': 60,
    'decrease_font_step_size': 1,
    'global_n_lines_max': 6,

    'vocab_font_sizes': {
        'words': 30
    },
    'word_index': {
        'font_name': 'Arial Black',
        'font_size': 36,
        'x': 30,
        'y': 30,
        'color1': "#000000",
        'color2': "#777777",
    },
    'previous_word': {
        'font_name': hanzi_font_path,
        'font_size': 12,
        'spacing': 6,
        'line_length': 1100,
        'n_lines_max': 4,
        'x': 20,
        'y': 75,
        'color': "#777777",
    },
    'logo': {
        'font_name': 'Arial Black',
        'font_size': 20,
        'x': 40,
        'y': 40,
        'color1': "#000080",
        'color2': "#1E90FF",
    },
    'footer_line': {
        'y': 100,
        'x': 10,
        'color': "#1E90FF",
        'width': 4,
    },

    'vocab_slide': {
        'chinese': {
            'y': 80,
            'font_size': 40,
            'spacing': 18,
            },
        'english': {
            'y': 430,
            'font_size': 35,
            'spacing': 18,
            },
    },

    'icon_configs': {
        'file_suffix': '_chinese', # UPDATE ON NEW VIDEO
        'word': '骑行绿道或湖边散步 免费惬意', # UPDATE ON NEW VIDEO
        'border_color_hex': "#1E90FF",
        'border_width': 30,
    },
}

# Non-vocab slide configs
subtitle = {
    'chinese': '武汉旅游攻略',
    'pinyin': 'Wǔhàn lǚyóu gōnglüè',
    'english': 'Wuhan tourist strategy',
    }  # UPDATE ON NEW VIDEO
video_structure_tup = ('Spoken in Chinese', '用中文说')
# UPDATE ON NEW VIDEO
nonvocab_slides = {
    'intro': {
        'chinese': f"我的普通话数据库视频 {video_number}",
        'pinyin': f"wǒ de pǔtōnghuà shùjùkù shìpín {video_number}",
        'english': f"My Mandarin Chinese Database Video {video_number}",
        'clip_index': 0,
        'change_index': -2,
        'pause_ms': 500,

        'channel_title': ('My Mandarin Database', '我的普通话数据库'),
        'video_number': (f'Video #{video_number}', f'视频#{video_number}'),
        'video_name': (subtitle['english'], subtitle['chinese']),
        'video_structure': video_structure_tup,
        'count_str': ("", ""),
        'duration_str': ('{audio_duration_minutes:.0f} minutes', '{audio_duration_minutes:.0f}分钟'),
        'feedback': ('If you have any questions, suggestions, or feedback\nplease leave a comment', '如果你有任何问题、建议或反馈\n请留言'),

        'x_bias_english_side': 80,
        'text_configs': [
            {
            'font_name': hanzi_font_path,
            'font_size': 32,
            'y': 100,
            'spacing': 20,
            'align': 'center',
            'fill': "#000000",
            },
            {
            'font_name': hanzi_font_path,
            'font_size': 24,
            'y': 300,
            'spacing': 10,
            'align': 'center',
            'fill': "#555555",
            },
            ]
    },

    'outro': {
        'chinese': '如果你有任何问题、建议或反馈，请留言。请点赞并订阅。',
        'pinyin': 'Rúguǒ nǐ yǒu rènhé wèntí, jiànyì huò fǎnkuì, qǐng liúyán. Qǐng diǎn zàn bìng dìngyuè.',
        'english': 'If you have any questions, suggestions, or feedback, please leave a comment. Please like and subscribe.',
        'clip_index': -1,
        'change_index': None,
        'pause_ms': 500,

        'y_top': 20,
        'y_bottom': 80,
        'x_top': 20,
        'spacing': 0,
        'font_size': 13,
        'fill': '#000000',
        'align': 'left',
        'col_space': 5,
        'col_space_big': 10,
        'definition_configs':{
            'chinese': {'x_offset': 0, 'x_max': 450, 'font_path': hanzi_font_path},
            'english': {'x_offset': None, 'x_max': 800, 'font_path': hanzi_font_path},
        }
    }
}

subtitle_text_configs = {
    'font_size': 20,
    'font_name': hanzi_font_path,
    'y': 640,
    'spacing': 5,
    'align': 'center',
    'fill': "#000000",
}
